Update test-release-web.yml

diff --git a/.github/workflows/test-release-web.yml b/.github/workflows/test-release-web.yml
--- a/.github/workflows/test-release-web.yml
+++ b/.github/workflows/test-release-web.yml
@@ -1,4 +1,4 @@
-name: Create Release and Upload Build Artifacts
+name: Create Release and Upload Build Artifacts Android
 
 on:
   push:
@@ -7,16 +7,14 @@ on:
 
 jobs:
   build_and_deploy:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
       - name: Shortify commit sha
-        shell: bash
         run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT
         id: shortify_commit
 
       - name: Get branch
-        shell: bash
         run: echo "ref_short=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
         id: get_branch
 
@@ -31,9 +29,21 @@ jobs:
       - name: Get stable flutter
         uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.22.x'
-          channel: 'stable'
+          flutter-version: '3.13.0'  # Замените на вашу версию
 
+      # Установка Java 17
+      - name: Install Java 17
+        run: |
+          sudo apt update
+          sudo apt install openjdk-17-jdk -y
+          sudo update-alternatives --config java
+          echo "JAVA_HOME set to /usr/lib/jvm/java-17-openjdk-amd64"
+
+      # Установим Java 17 для Gradle
+      - name: Set Java 17 for Gradle
+        run: echo "org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.gradle/gradle.properties
+
+      # Подготовка build директории
       - name: Prepare build directory
         run: |
           flutter clean
@@ -41,54 +51,35 @@ jobs:
           rm -rf web/src/mm2/*
           rm -rf web/src/kdfi/*
           rm -rf web/dist/*
-        env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Fetch packages and generate assets
         run: |
-          echo "Running \`flutter build\` to generate assets for the deployment build"
-          flutter pub get > /dev/null 2>&1
-          flutter build web --release > /dev/null 2>&1 || true
-          flutter pub get > /dev/null 2>&1
+          flutter pub get
+          flutter build apk --release || true
+          flutter pub get
           echo "Done fetching packages and generating assets"
 
-      - name: Build GRMS Wallet web
+      - name: Build GRMS Wallet Android
         run: |
           flutter doctor -v
-          flutter build web --csp --profile --no-web-resources-cdn
+          flutter build apk --release
 
       - name: Validate build
         run: |
-          if [ ! -f build/web/dist/*.wasm ]; then
-            echo "Error: Web build failed. No wasm file found in build/web/dist/"
-            exit 1 
-          fi
-          if ! cmp -s web/index.html build/web/index.html; then
-            echo "Error: Web build failed. index.html is not equal to the source index.html"
-            exit 1
-          fi
-          if git diff --exit-code web/index.html; then
-            echo "Error: Web build failed. index.html has no uncommitted changes"
-            exit 1
-          fi
-          if [ ! -f build/web/assets/AssetManifest.bin ]; then
-            echo "Error: AssetManifest.bin file not found."
-            exit 1
-          fi
-          if ! strings build/web/assets/AssetManifest.bin | grep -q "assets/coin_icons/png/kmd.png"; then
-            echo "Error: Coin icon not found in AssetManifest.bin"
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "Error: Android build failed. No APK file found."
             exit 1
           fi
 
       - name: Archive build artifacts
         run: |
-          zip -r build-web.zip build/web/
+          zip -r build-android.zip build/app/outputs/flutter-apk/
 
       - name: Upload build as artifact
         uses: actions/upload-artifact@v3
         with:
-          name: web-build
-          path: build-web.zip
+          name: android-build
+          path: build-android.zip
 
       - name: Create Release
         id: create_release
@@ -101,13 +92,12 @@ jobs:
           draft: false
           prerelease: false
 
-
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: build-web.zip
-          asset_name: build-web.zip
+          asset_path: build-android.zip
+          asset_name: app-release.zip  # Исправляем расширение на .zip
           asset_content_type: application/zip
